// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// BreadcrumbFetcher is an autogenerated mock type for the BreadcrumbFetcher type
type BreadcrumbFetcher struct {
	mock.Mock
}

// FetchBreadcrumb provides a mock function with given fields: baseURL, keyword
func (_m *BreadcrumbFetcher) FetchBreadcrumb(baseURL string, keyword string) (map[string]interface{}, error) {
	ret := _m.Called(baseURL, keyword)

	if len(ret) == 0 {
		panic("no return value specified for FetchBreadcrumb")
	}

	var r0 map[string]interface{}
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (map[string]interface{}, error)); ok {
		return rf(baseURL, keyword)
	}
	if rf, ok := ret.Get(0).(func(string, string) map[string]interface{}); ok {
		r0 = rf(baseURL, keyword)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(baseURL, keyword)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewBreadcrumbFetcher creates a new instance of BreadcrumbFetcher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBreadcrumbFetcher(t interface {
	mock.TestingT
	Cleanup(func())
}) *BreadcrumbFetcher {
	mock := &BreadcrumbFetcher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
