// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// CategoryDetailsFetcher is an autogenerated mock type for the CategoryDetailsFetcher type
type CategoryDetailsFetcher struct {
	mock.Mock
}

// FetchCategoryDetails provides a mock function with given fields: baseURL, slug, pt, limit
func (_m *CategoryDetailsFetcher) FetchCategoryDetails(baseURL string, slug string, pt string, limit string) (map[string]interface{}, error) {
	ret := _m.Called(baseURL, slug, pt, limit)

	if len(ret) == 0 {
		panic("no return value specified for FetchCategoryDetails")
	}

	var r0 map[string]interface{}
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string, string, string) (map[string]interface{}, error)); ok {
		return rf(baseURL, slug, pt, limit)
	}
	if rf, ok := ret.Get(0).(func(string, string, string, string) map[string]interface{}); ok {
		r0 = rf(baseURL, slug, pt, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(string, string, string, string) error); ok {
		r1 = rf(baseURL, slug, pt, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewCategoryDetailsFetcher creates a new instance of CategoryDetailsFetcher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCategoryDetailsFetcher(t interface {
	mock.TestingT
	Cleanup(func())
}) *CategoryDetailsFetcher {
	mock := &CategoryDetailsFetcher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
