// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	requests "smartours/requests"

	mock "github.com/stretchr/testify/mock"
)

// CategoryPageFetcher is an autogenerated mock type for the CategoryPageFetcher type
type CategoryPageFetcher struct {
	mock.Mock
}

// FetchCategoryPage provides a mock function with given fields: baseURL, slug
func (_m *CategoryPageFetcher) FetchCategoryPage(baseURL string, slug string) (requests.CategoryData, error) {
	ret := _m.Called(baseURL, slug)

	if len(ret) == 0 {
		panic("no return value specified for FetchCategoryPage")
	}

	var r0 requests.CategoryData
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (requests.CategoryData, error)); ok {
		return rf(baseURL, slug)
	}
	if rf, ok := ret.Get(0).(func(string, string) requests.CategoryData); ok {
		r0 = rf(baseURL, slug)
	} else {
		r0 = ret.Get(0).(requests.CategoryData)
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(baseURL, slug)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewCategoryPageFetcher creates a new instance of CategoryPageFetcher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCategoryPageFetcher(t interface {
	mock.TestingT
	Cleanup(func())
}) *CategoryPageFetcher {
	mock := &CategoryPageFetcher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
