// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// PropertyDetailsFetcher is an autogenerated mock type for the PropertyDetailsFetcher type
type PropertyDetailsFetcher struct {
	mock.Mock
}

// FetchPropertyDetails provides a mock function with given fields: baseURL, ids
func (_m *PropertyDetailsFetcher) FetchPropertyDetails(baseURL string, ids string) (map[string]interface{}, error) {
	ret := _m.Called(baseURL, ids)

	if len(ret) == 0 {
		panic("no return value specified for FetchPropertyDetails")
	}

	var r0 map[string]interface{}
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (map[string]interface{}, error)); ok {
		return rf(baseURL, ids)
	}
	if rf, ok := ret.Get(0).(func(string, string) map[string]interface{}); ok {
		r0 = rf(baseURL, ids)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(baseURL, ids)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewPropertyDetailsFetcher creates a new instance of PropertyDetailsFetcher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPropertyDetailsFetcher(t interface {
	mock.TestingT
	Cleanup(func())
}) *PropertyDetailsFetcher {
	mock := &PropertyDetailsFetcher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
