// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	requests "smartours/requests"

	mock "github.com/stretchr/testify/mock"
)

// PropertiesFetcher is an autogenerated mock type for the PropertiesFetcher type
type PropertiesFetcher struct {
	mock.Mock
}

// FetchProperties provides a mock function with given fields: baseURL, params
func (_m *PropertiesFetcher) FetchProperties(baseURL string, params requests.PropertyParams) (map[string]interface{}, error) {
	ret := _m.Called(baseURL, params)

	if len(ret) == 0 {
		panic("no return value specified for FetchProperties")
	}

	var r0 map[string]interface{}
	var r1 error
	if rf, ok := ret.Get(0).(func(string, requests.PropertyParams) (map[string]interface{}, error)); ok {
		return rf(baseURL, params)
	}
	if rf, ok := ret.Get(0).(func(string, requests.PropertyParams) map[string]interface{}); ok {
		r0 = rf(baseURL, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(string, requests.PropertyParams) error); ok {
		r1 = rf(baseURL, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewPropertiesFetcher creates a new instance of PropertiesFetcher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPropertiesFetcher(t interface {
	mock.TestingT
	Cleanup(func())
}) *PropertiesFetcher {
	mock := &PropertiesFetcher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
