// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// PropertyImagesFetcher is an autogenerated mock type for the PropertyImagesFetcher type
type PropertyImagesFetcher struct {
	mock.Mock
}

// FetchPropertyImages provides a mock function with given fields: baseURL, propertyId
func (_m *PropertyImagesFetcher) FetchPropertyImages(baseURL string, propertyId string) (map[string]interface{}, error) {
	ret := _m.Called(baseURL, propertyId)

	if len(ret) == 0 {
		panic("no return value specified for FetchPropertyImages")
	}

	var r0 map[string]interface{}
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (map[string]interface{}, error)); ok {
		return rf(baseURL, propertyId)
	}
	if rf, ok := ret.Get(0).(func(string, string) map[string]interface{}); ok {
		r0 = rf(baseURL, propertyId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(baseURL, propertyId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewPropertyImagesFetcher creates a new instance of PropertyImagesFetcher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPropertyImagesFetcher(t interface {
	mock.TestingT
	Cleanup(func())
}) *PropertyImagesFetcher {
	mock := &PropertyImagesFetcher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
